name: delasole
favicon: null
layout_spectrum: 0.00546
typography_spectrum: 0.9399545409251004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7845413531176746
  lightness: 0.9904492637142539
  saturation: 0.675016105407849
  rhythmicContrast: 0.6069249741267413
purpose: []
